baseURL = "https://www.montferret.dev/"
languageCode = "en-us"
title = "Ferret"
theme = "ferret"

[permalinks]
    pages = "/:title/"

[menu]

  [[menu.left]]
    identifier = "overview"
    name = "Overview"
    title = "Project overview"
    url = "/overview/"
    weight = 1

  [[menu.left]]
    identifier = "guide"
    name = "Guide"
    title = "User guide"
    url = "/guide/"
    weight = 2

  [[menu.left]]
    identifier = "api"
    name = "Api"
    title = "Api"
    url = "/api/"
    weight = 3

  [[menu.left]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.right]]
    identifier = "donate"
    name = "Donate"
    title = "Open collective"
    url = "https://opencollective.com/ferret"
    weight = 5

  [[menu.right]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub repository"
    url = "https://github.com/MontFerret/ferret"
    weight = 6