baseURL = "https://vibrant-euclid-cf9207.netlify.com/"
languageCode = "en-us"
title = "Ferret"
theme = "ferret"

[permalinks]
    pages = "/:title/"

[menu]

  [[menu.main]]
    identifier = "guidelines"
    name = "Guidelines"
    title = "Project Guidelines"
    url = "/guidelines/"
    weight = 2

  [[menu.main]]
    identifier = "quickstart"
    name = "Quick Start"
    title = "Quick Start"
    url = "/quickstart/"
    weight = 1 

  [[menu.main]]
    identifier = "api"
    name = "API"
    title = "API"
    url = "/api/"
    weight = 3

  [[menu.main]]
    identifier = "faqs"
    name = "FAQs"
    title = "Frequently Asked Questions"
    url = "/faqs/"
    weight = 3