baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ferret"
theme = "Ferret"

[permalinks]
pages = "/:title/"

[menu]

  [[menu.main]]
    identifier = "guidelines"
    name = "Guidelines"
    title = "Project Guidelines"
    url = "/guidelines/"
    weight = 1

  [[menu.main]]
    identifier = "quickstart"
    name = "Quick Start"
    title = "Quick Start"
    url = "/quickstart/"
    weight = 2

  [[menu.main]]
    identifier = "api"
    name = "API"
    title = "API"
    url = "/api/"
    weight = 3

  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    title = "Frequently Asked Questions"
    url = "/faq/"
    weight = 3